### ISSUE TITLE
Some inconsistent numbers

### ISSUE THREAD

**Issue by ssz360** [pcm-dpc/COVID-19#358] opened 2020-03-25 06:50 UTC
Thank you for your great work.
I've created an interactive map of Covid-19 outbreak in Italy based on this repository's data. when I was checking the map I was noticed some problems, for example:

The infected number of people in Benevento: (The numbers must be ascending but they aren't.)
10-03-2020:  4
11-03-2020:  2

Vibo Valentia:
14-03-2020:  17
15-03-2020:  6

Arezzo:
18-03-2020:  142
19-03-2020:  113
![image](https://user-images.githubusercontent.com/5657438/77509503-75da3b80-6e8a-11ea-8237-2d5de43fcdd4.png)

Frosinone:
18-03-2020:  54
19-03-2020:  48

Sud Sardegn:
14-03-2020:  5
15-03-2020:  3

The file I'm using:
dati-province/dpc-covid19-ita-province.csv

The map: https://github.com/ssz360/Covid-19-Outbreak

**Comment by duckyb** [comment] 2020-03-25 11:54
Adding to this:

Biella:
08-03-2020: 19
09-03-2020: 18

Torino:
01-03-2020: 49
02-03-2020: 6

Verbatano-Cusio-Ossola:
08-03-2020: 13
09-03-2020: 11

Vercelli:
05-03-2020: 8
06-03-2020: 7
08-03-2020: 15
09-03-2020: 11

**Comment by FedericoStra** [comment] 2020-03-25 16:12
> The numbers must be ascending but they aren't.

I believe you are looking at the field `totale_attualmente_positivi`. This means the number of people *currently* positive. Some people can become affected by the virus, some other people can cease to be positive by recovering or dying. There is no reason for this number to be weakly increasing.

**Comment by FedericoStra** [comment] 2020-03-25 17:09
# This was my original comment

> The numbers must be ascending but they aren't.

I believe you are looking at the field `totale_attualmente_positivi`. This means the number of people *currently* positive. Some people can become infected by the virus, some other people can cease to be positive by recovering or dying. There is no reason for this number to be weakly increasing.

To summarize:
- `totale_attualmente_positivi`: number of people currently positive
- `totale_casi`: number of the people infected by the virus at some point in time (even if they have now recovered or died)
- the number of new infections per day is `nuovi_casi = totale_casi(today) - totale_casi(yesterday)`
- the variation in the number of people currently positive is `nuovi_attualmente_positivi = attualmente_positivi(today) - attualmente_positivi(yesterday) = nuovi_casi - recovered(today) - deceased(today)`

# Update

You are right, the column title is indeed `totale_casi`. This is very strange. There are quite a lot in fact. Here is a table where `delta_totale_casi` is the difference `totale_casi` of the day minus `totale_casi` of the previous day:
```
               data  codice_provincia denominazione_provincia  totale_casi  delta_totale_casi
2020-02-26 18:00:00                47                 Pistoia            0               -1.0
2020-02-27 18:00:00                 1                  Torino            2               -1.0
2020-02-27 18:00:00                48                 Firenze            1               -1.0
2020-02-28 18:00:00                72                    Bari            0               -1.0
2020-02-29 17:00:00                48                 Firenze            5               -2.0
2020-03-01 17:00:00                 9                  Savona           19              -22.0
2020-03-02 17:00:00                 9                  Savona           16               -3.0
2020-03-02 17:00:00                 1                  Torino            6              -43.0
2020-03-02 17:00:00                48                 Firenze            4               -1.0
2020-03-02 17:00:00                54                 Perugia            1               -1.0
2020-03-03 17:00:00                67                  Teramo            3               -2.0
2020-03-03 17:00:00                32                 Trieste            2               -7.0
2020-03-04 17:00:00                63                  Napoli           17              -13.0
2020-03-04 17:00:00                 9                  Savona           19               -1.0
2020-03-06 18:00:00                40            Forlì-Cesena            3               -1.0
2020-03-06 18:00:00                 9                  Savona           15               -5.0
2020-03-06 18:00:00                 2                Vercelli            7               -1.0
2020-03-07 18:00:00                86                    Enna            0               -1.0
2020-03-08 18:00:00               108   Monza e della Brianza           59               -2.0
2020-03-09 18:00:00                96                  Biella           18               -1.0
2020-03-09 18:00:00                 1                  Torino           87               -2.0
2020-03-09 18:00:00               103    Verbano-Cusio-Ossola           11               -2.0
2020-03-09 18:00:00                 2                Vercelli           11               -4.0
2020-03-09 18:00:00                54                 Perugia           12               -3.0
2020-03-10 18:00:00               102           Vibo Valentia            1               -1.0
2020-03-10 18:00:00                58                    Roma           76              -15.0
2020-03-11 17:00:00                79               Catanzaro            2               -1.0
2020-03-11 17:00:00                78                 Cosenza            5               -1.0
2020-03-11 17:00:00                62               Benevento            2               -2.0
2020-03-11 17:00:00                61                 Caserta           26               -8.0
2020-03-11 17:00:00                55                   Terni           18               -6.0
2020-03-12 17:00:00                57                   Rieti            2               -1.0
2020-03-12 17:00:00                56                 Viterbo            5               -5.0
2020-03-12 17:00:00                92                Cagliari           11               -4.0
2020-03-12 17:00:00                29                  Rovigo           13               -1.0
2020-03-14 17:00:00               101                 Crotone            5               -2.0
2020-03-15 17:00:00               102           Vibo Valentia            6              -11.0
2020-03-15 17:00:00                93               Pordenone           42               -3.0
2020-03-15 17:00:00                32                 Trieste          140               -8.0
2020-03-15 17:00:00               111            Sud Sardegna            3               -2.0
2020-03-16 17:00:00                31                 Gorizia           16              -15.0
2020-03-17 17:00:00                30                   Udine          145               -7.0
2020-03-17 17:00:00                 8                 Imperia           76               -2.0
2020-03-18 17:00:00                70              Campobasso           24               -1.0
2020-03-19 17:00:00                60               Frosinone           48               -6.0
2020-03-19 17:00:00                51                  Arezzo          113              -29.0
2020-03-21 17:00:00                77                  Matera            8               -1.0
```

There are then over 100 more with `denominazione_provincia = "In fase di definizione/aggiornamento"`. I don't know how to treat them...

Here is the code used to find them:
```python3
import pandas as pd

province = pd.read_csv("dpc-covid19-ita-province.csv")
province['delta_totale_casi'] = province.groupby('denominazione_provincia').totale_casi.diff()

suspicious = province.loc[
        province.delta_totale_casi < 0,
        ('data', 'codice_provincia', 'denominazione_provincia', 'totale_casi', 'delta_totale_casi')]

# Province with a name
print(suspicious[~suspicious.denominazione_provincia.str.contains('/')])

# Province without a name
print(suspicious[suspicious.denominazione_provincia.str.contains('/')])
```

I believe this is must be caused by people moving from one province to another. I know that they are transferring patients between hospitals, so this might be the reason.

**Comment by DisherProject** [comment] 2020-03-26 12:59
> Arezzo:
18-03-2020: 142
19-03-2020: 113

As it is stated [here](https://www.toscana-notizie.it/web/toscana-notizie/-/coronavirus-152-nuovi-casi-in-toscana.-in-tutto-sono-1.482-i-contagi-dall-inizio), the data have been communicated incorrectly, by the local ASL, in march 18. The correct number is 91.

That may be the cause of other inconsistencies

**Comment by umbros** [comment] 2020-06-02 14:50
Inconsistencies can be caused by partial data. We write notice about that.

**Closed by umbros** 2020-06-02 14:50 UTC
