### ISSUE TITLE
Unexpected token ß in JSON

### ISSUE THREAD

**Issue by arpitux** [pcm-dpc/COVID-19#943] opened 2020-11-23 19:15 UTC
Hello,

there is an unexpected character added in this JSON API -
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-province.json

![image](https://user-images.githubusercontent.com/9971612/100005034-58c98400-2dee-11eb-826c-121647a2bb9b.png)

- Arpit

**Comment by pinoli** [comment] 2020-11-23 19:38
+1 on this, it breaks JSON parsing everywhere

**Comment by stesforz** [comment] 2020-11-23 20:44
Fix it please, it breaks JSON parsing and doesn't allow our application to update. thanx

**Comment by miccoli** [comment] 2020-11-23 21:15
Please see also the failure of my test suite (PR #847) at <https://github.com/miccoli/COVID-19/runs/1444432722?check_suite_focus=true>.

**Comment by miccoli** [comment] 2020-11-23 21:42
Duplicate of #941

**Comment by lp74** [comment] 2020-11-24 11:06
Please, this issue breaks parsing

**Comment by Gioee** [comment] 2020-11-24 11:55
+1 please fix this.

**Comment by alexodus** [comment] 2020-11-24 16:07
+1

**Comment by miccoli** [comment] 2020-11-24 19:54
Apparently this has been corrected in bc9d167.

**Closed** 2020-11-28 19:58 UTC
