### ISSUE TITLE
Json format error in dpc-covid19-ita-province.json

### ISSUE THREAD

**Issue by tatomix** [pcm-dpc/COVID-19#952] opened 2020-11-29 10:35 UTC
`There is a Json format error in dpc-covid19-ita-province.json row 4`

**Comment by floatingpurr** [comment] 2020-11-29 14:37
Duplicate of #948 (Still waiting for a fix).

**Comment by ricir** [comment] 2020-11-29 17:06
Seems to be fixed now.

**Comment by floatingpurr** [comment] 2020-11-30 09:39
Looks like this kind of issues is fixed in the next data release 24h later

**Closed** 2020-12-27 16:14 UTC
